### ISSUE TITLE
Using image upload on Blazer Server causes a crash

### ISSUE THREAD

**Issue by LoveCSharp** [erossini/BlazorMarkdownEditor#12]
When using Blazor MarkdownEditor in Blazor Server, if image upload is turned on(UploadImage="true" ImageUploadEndpoint="..."),drag or copy the image to upload, the page will have an error "Attempting to reconnect to the server".Here's the log in the chrome console:
[2022-06-19T06:07:42.805Z] Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.
log @ blazor.server.js:1
_stopConnection @ blazor.server.js:1
transport.onclose @ blazor.server.js:1
_close @ blazor.server.js:1
stop @ blazor.server.js:1
_stopInternal @ blazor.server.js:1
await in _stopInternal(异步)
stop @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
o.onmessage @ blazor.server.js:1

**Comment by erossini** [comment]
Does your solution start with multiple projects `MarkdownEditorDemo.Api` and `MarkdownEditorDemo`?

**Comment by erossini** [comment]
I close now this issue. I hope the code is working.

**Comment by oolleegg55** [comment]
If you're using the [Interactive Server render mode](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-9.0), you might run into issues related to the maximum SignalR message size.

To fix this, simply raise the limit:

```csharp
builder.Services.AddSignalR(options =>
{
    options.MaximumReceiveMessageSize = 10 * 1024 * 1024; // 10 MB
});
```

Also, if you're using Interactive Server, you don't need a separate API for image saving. You can handle it directly in your `CustomImageUpload` method.
