### ISSUE TITLE
Leads on fixing mermaid and highlightjs compatibility?

### ISSUE THREAD

**Issue by davidreneuw** [erossini/BlazorMarkdownEditor#17]
Any leads on how to make both mermaid and highlightjs work at the same time? Ive been building custom highlightjs builds to avoid mermaid codeblocks with no success.
Just interested in seeing if it is possible at all from your point of view

**Comment by erossini** [comment]
Sorry, I missed your message. I don't have at the moment an implementation for mermaid and highlights working together in this component. Please let me know if you made any progress on that.

Thank yo so much,
Enrico
