### ISSUE TITLE
ImageMaxSize not working

### ISSUE THREAD

**Issue by wanglvhang** [erossini/BlazorMarkdownEditor#23]
when upload image file size is bigger than specified or default(2MB), the image file will still been uploaded.
tested on Blazor WebAssembly

<MarkdownEditor @ref="markdownEditor" @bind-Value="SelectedEvent.content"
                ValueHTMLChanged="OnMarkdownValueHTMLChanged"
                ImageUploadStarted="UploadImageStarted"
                ImageUploadEndpoint=@markdownImageUploadEndpoint
                ImagePathAbsolute="true"
                UploadImage="true"/>

**Comment by erossini** [comment]
OK, I'll check that

**Comment by wanglvhang** [comment]
> OK, I'll check that. Did you close the ticket because you fixed it?

i check the source code, i don't see any size checking logic in MarkdownEditor.razor UploadFile method, so i guess may be this function is not in the scope right now?

**Comment by erossini** [comment]
I haven't close the ticket.
