### ISSUE TITLE
How can we create  HTMLString without loading MarkdownEditor

### ISSUE THREAD

**Issue by manish-karn** [erossini/BlazorMarkdownEditor#27]
### Discussed in https://github.com/erossini/BlazorMarkdownEditor/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **manish-karn** April 11, 2024</sup>
How can we generate HTMLString without loading MarkdownEditor? like MarkDig.Markdown.ToHTML() , I could not find any api exist , any code sample will be great appreciated, it is possible to show MarkdownEditor and call ValueHTMLChanged and hide MarkdownEditor immediately, but that causes annoying flicking UI</div>

**Comment by erossini** [comment]
You can use libraries like `MarkDig`. It is possible to use the `MarkdownEditor` without displaying it. Just create an instance of it like

```
MarkdownEditor Markdown1;
```

and then use its properties and methods.
