### ISSUE TITLE
Where is the commit for the 8.0.0 version release?

### ISSUE THREAD

**Issue by jherbert** [erossini/BlazorMarkdownEditor#31]
There was a 8.0.0 release for this package in nuget https://www.nuget.org/packages/PSC.Blazor.Components.MarkdownEditor  however there is no recent commits in the repository? The nuget package seems to reference a commit of `14c1f601a62ed34d67b28f2a73fc87823760c605` but doesn't exist here.

Making sure something malicious is not going on here...

**Comment by erossini** [comment]
I have a repo in my personal Azure DevOps and will align the code. Probably I forgot to do so this version. Let me check

**Comment by erossini** [comment]
Today, I updated the full repository. There is a new [EasyMDE](https://github.com/erossini/EasyMarkdownEditor) managed by myself.  There is a lot of fixes in this new version.
