### ISSUE TITLE
ValueChanged eventcallback always return the initial value of markdown text

### ISSUE THREAD

**Issue by RosaShellPicker** [erossini/BlazorMarkdownEditor#4]
I handled the ValueChange event when using BlazorMarkdownEditor, but when I typed in the editor,  the value returned as a parameter never changed. We need to restore the markdown text in database.

**Comment by erossini** [comment]
I'll check that. Give you an answer asap.

**Comment by erossini** [comment]
Hi @RosaShellPicker, 
there was an issue related to the variation on "Component changing its Parameter value". I fixed it and an update for the component is on its way.

Now, you have to change slightly the code for adding a new MarkdownEditor like that

```
<MarkdownEditor @bind-Value="@markdownValue" 
                ValueHTMLChanged="@OnMarkdownValueHTMLChanged" />
```

**Comment by RosaShellPicker** [comment]
@erossini  Thanks for replying so rapidly, and the issue is resolved.  You are amazing!
