### ISSUE TITLE
[question] License 

### ISSUE THREAD

**Issue by lukblazewicz** [erossini/BlazorMarkdownEditor#6]
I cannot see any licensing information regarding this package. Is BlazorMarkdownEditor free to use for commercial purposes?

**Comment by erossini** [comment]
Hi,
thank you for your question. A lot of people sent me the same question. My components ([MarkdownEditor](https://www.puresourcecode.com/dotnet/blazor/markdown-editor-component-for-blazor), [DataTable](https://www.puresourcecode.com/dotnet/net-core/datatable-component-for-blazor), [SVG Icon](https://www.puresourcecode.com/dotnet/blazor/svg-icons-and-flags-for-blazor) and others that you find on my [GitHub](https://github.com/erossini)) are freeware. 

I ask you to contribute to the project in one of the following ways:

- sending your feedback
- highlight bugs
- ask for improvement
- submit code and fixes
- share the project
- share my website [PureSourceCode.com](https://www.puresourcecode.com/)

If you don't know how to do it or you:

- want to support this project
- find very useful this project and it saves you a lot of time and work
- like to sustain my work
- want to pay my a beer
- are using this component for commercial purpose and you want to set your conscience at rest and/or put a hand on one's heart 😂

then, you can buy one of the support licence I created. There are different prices. The amount is your decision. You find have a full list on [PureSourceCode Shop](https://www.puresourcecode.com/shop)

The contribution gives you:

- dedicate email support
- priority access to the support
- fast bug fix
- receive preview and beta of the components
- help to fix your code with [Visual Studio Live Share](https://www.puresourcecode.com/tools/a-guide-to-remote-development-with-visual-studio-live-share/)

**Comment by 3DExtended** [comment]
Hello @erossini, 

Thank you very much for this awesome repository!
As I am looking into using this package I am legally required to ask for a license. Could you maybe add a license to this repo? If you'd like I could add an MIT license as a PR to this repo.

This addition would be really awesome and I am looking forward to using this editor!

Best wishes!

**Comment by erossini** [comment]
Hello @3DExtended,
I have just added the licence.
