### ISSUE TITLE
Ability to disable Spell check

### ISSUE THREAD

**Issue by Duster96** [erossini/BlazorMarkdownEditor#7]
I would like to have the ability to disable spell check on markdown editor. Is it possible now?

It is example below:
![image](https://user-images.githubusercontent.com/20935584/155078098-9d53be7a-6792-4867-9d26-62f67239e8c5.png)

**Comment by erossini** [comment]
At the moment there is no option for disable the spell check. I'll add it in the next release (very soon).

**Comment by Duster96** [comment]
I am waiting! Thank you for the quick response!
