### ISSUE TITLE
OnInitializedAsync Value initialization

### ISSUE THREAD

**Issue by dor1202** [erossini/BlazorMarkdownEditor#9]
Hi!
First of all, amazing component.
Second,
I have 2 issues in 1.
1. OnInitialized function will update the value but OnInitializedAsync will not when using async await for http client.
2. there isn't any Toolbar documentation.

Adding a code sample for the issue:

`
    ``<MarkdownEditor  Value="@Value" Toolbar={????}/>``

    @code {
       [Parameter]
       public string Value { get; set; } = string.Empty;

       protected override async Task OnInitializedAsync()
       {
            // Will Not Work
            var Http = new HttpClient() { BaseAddress = new Uri(MyNavigationManager.BaseUri) };
            var tmp = await Http.GetStringAsync("md/ReleaseNotesTemplate.md");
            Value = tmp;
       }

       protected override void OnInitialized()
       {
          // Will Work
          Value = "# Sample Template For comments";
       }
    }
`

**Comment by erossini** [comment]
Hello! You're right, there is not a big documentation about the toolbar but you can refer to the official website for it for now.

Did you try to call `StateHasChanged()` after setting a new `Value`?

**Comment by dor1202** [comment]
Hello @erossini , thank you for the response.
Yes, I tried to call `StateHasChanged()`

**Comment by erossini** [comment]
Have you done any progress? I've just came back from holidays and I'll look at it in the next few days.

**Comment by dor1202** [comment]
Hi, @erossini hope you had a good holiday.
Unfortunately, I couldn't find a solution to the problem even after investing a few days.
Hope you will find the bug.
I will be happy to be notified if any progress is done!

**Comment by erossini** [comment]
@dor1202 Hey! I found the issue! In an hour you have the new version. Also, you will find some examples of toolbar and the documentation. 

The live example will available [here](https://markdown.puresourcecode.com/).

**Comment by dor1202** [comment]
@erossini Wow! amazing, I will update and check this out for sure!

**Comment by Seikon** [comment]
For me worked render component after async operations has finished on OnInitializedAsync. I control the whole flow with a flag (Loaded) that indicates all operations has finished:

@if(!Loaded)
{
    <h3>Cargando</h3>
}
else
{
    <div class="row">

        <div class="col-md">
            <MarkdownEditor @bind-Value="@MarkdownValue" MaxHeight="300px"
                            ValueHTMLChanged="@OnMarkdownValueHTMLChanged"
                            SpellChecker="false" />
        </div>

        <div class="col-md">

            <h3>Result</h3>
            @((MarkupString)MarkdownHTML)

        </div>
        <div>
            <button onclick="@GuardarMarkdown()">Guardar</button>
        </div>

    </div>
